# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'2.2.6'

In [4]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.29  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.29
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.29  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.29
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    na

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
nums = np.zeros([10], dtype=np.int64)

int16 -> 16 bits = 2 bytes

int64 -> 64 bits = 8 bytes

In [6]:
nums.shape

(10,)

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
nums.itemsize

8

In [8]:
nums.size * nums.itemsize

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
null = np.zeros(10)
null[4] = 1
null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
z = np.arange(10, 50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
z = z[::-1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
z = np.arange(0, 9)
z = z.reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [16]:
z = np.array([1,2,0,0,4,0])

In [17]:
z.shape

(6,)

In [19]:
np.nonzero(z)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [36]:
s = (3,3,3) # this can we list but tuple prefeble due to numpy call internally tuple(shape)

In [37]:
z = np.random.random(s)
z

array([[[0.96697181, 0.25902672, 0.9231941 ],
        [0.19460214, 0.82875272, 0.79488728],
        [0.80360426, 0.19127422, 0.87178506]],

       [[0.6249581 , 0.86763351, 0.36071044],
        [0.46440927, 0.159955  , 0.31605068],
        [0.65100651, 0.74040764, 0.52375371]],

       [[0.77156703, 0.32040175, 0.07155475],
        [0.05934515, 0.9867343 , 0.72226597],
        [0.03245336, 0.3791434 , 0.95609867]]])

In [38]:
z.shape

(3, 3, 3)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [40]:
z = np.random.random((10,10))
z.shape

(10, 10)

In [45]:
z.min()

np.float64(0.01860645269002692)

In [46]:
z.max().item()

0.9946773644157828

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [47]:
z = np.random.random(30)
z.mean()

np.float64(0.4509469204028458)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [48]:
z = np.zeros((4,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
z[:,0] = 1
z[:, -1] = 1
z[0,:] = 1
z[-1,:] = 1

In [52]:
z

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [53]:
z = np.ones((4,4))
z[1:-1, 1:-1] = 0
z

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [61]:
z = np.ones((4,4))
v_col = np.array([0,0,0,0]).reshape(-1,1)
z = np.concatenate([z, v_col], axis=1)
z = np.concatenate([v_col, z], axis=1)
h_row = np.array([0,0,0,0,0,0]).reshape(1,-1)
z = np.concatenate([h_row, z], axis=0)
z = np.concatenate([z, h_row], axis=0)
z

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [62]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [63]:
z = np.ones((5,5))
z[:, [0,-1]] = 0
z[[0,-1], :] = 0
z

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [65]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan-np.nan)

nan
False
False
nan


In [66]:
0.3 == 3 * 0.1

False

In [67]:
np.nan in set([np.nan])

True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [77]:
z = np.diag((1,2,3,4), k =-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [91]:
z = np.ones((4,4))
z[::2,1::2] = 0
z[1::2,::2] = 0
z

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [94]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [96]:
# np.tile(A, reps) constructs a new array by repeating A according to the pattern specified in reps.

z = np.tile([[1,0], [0, 1]], (4,4))
z

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [102]:
z = np.random.choice(np.arange(5), size=(5,5))
print(z)
z = (z - np.mean(z)) / np.std(z)
print(np.mean(z))
print(z)

[[0 3 2 4 1]
 [1 0 3 0 3]
 [3 2 4 0 3]
 [2 4 0 3 1]
 [4 0 4 4 1]]
-9.769962616701378e-17
[[-1.36747438  0.60484444 -0.05259517  1.26228404 -0.71003477]
 [-0.71003477 -1.36747438  0.60484444 -1.36747438  0.60484444]
 [ 0.60484444 -0.05259517  1.26228404 -1.36747438  0.60484444]
 [-0.05259517  1.26228404 -1.36747438  0.60484444 -0.71003477]
 [ 1.26228404 -1.36747438  1.26228404  1.26228404 -0.71003477]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [106]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

pixels = np.array((255, 0, 0, 255), dtype=color)
pixels["r"]

array(255, dtype=uint8)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [107]:
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.matmul(x, y)
z.shape

(5, 2)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
z = np.arange(10)
z[(z>3) and (z<10)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8, -9])

In [116]:
print(z[(z>1) & (z>2)])

[3]


In [1]:
import numpy as np

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [2]:
type(range(5))

range

In [7]:
print(sum(range(5),-5. -6)) # -6, -5, 0, 1, 2, 4, 5
# from numpy import *
print(np.sum(range(5),axis=-1))

-1.0
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [17]:
z = np.array([[2,1,3], [3,2,4]])
z**z

array([[  4,   1,  27],
       [ 27,   4, 256]])

In [18]:
z >> 2 #Shifts bits to the right (divides by 2ⁿ)

array([[0, 0, 0],
       [0, 0, 1]])

In [20]:
2 << z #Shifts bits to the left (multiplies by 2ⁿ)

array([[ 8,  4, 16],
       [16,  8, 32]])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [21]:
np.array(0) / np.array(0)

/tmp/ipykernel_154836/873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [22]:
np.array(0) // np.array(0)

/tmp/ipykernel_154836/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [25]:
np.array([np.nan]).astype(int).astype(float)
# You get a very large negative number — which is the smallest possible 64-bit integer (-2⁶³),
#  often used as a placeholder for "bad" conversions.

/tmp/ipykernel_154836/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [34]:
z = np.random.uniform(-10,+10,10)
z

array([ 2.0258755 , -5.85893545, -3.20356485, -9.72553621,  0.8236195 ,
        0.83123186, -6.19877051,  6.85546072, -8.01997003,  1.92416981])

In [36]:
z = np.copysign(np.abs(z), z)
z

array([ 2.0258755 , -5.85893545, -3.20356485, -9.72553621,  0.8236195 ,
        0.83123186, -6.19877051,  6.85546072, -8.01997003,  1.92416981])

In [35]:
print(np.copysign(np.ceil(np.abs(z)), z))

[  3.  -6.  -4. -10.   1.   1.  -7.   7.  -9.   2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [40]:
z1 = np.array([[1,2], [3,2], [6,4]])
z2 = np.array([[4,2], [3,3]])
print(np.intersect1d(z1, z2))

[2 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [43]:
defaults = np.seterr(all="ignore")
z = np.array(0) // np.array(0)
z

np.int64(0)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [44]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [45]:
np.datetime64('TODAY')

np.datetime64('2025-07-09')

In [49]:
np.datetime64('today') - np.timedelta64(1)

np.datetime64('2025-07-08')

In [50]:
np.datetime64('today') + np.timedelta64(1)

np.datetime64('2025-07-10')

In [52]:
np.datetime64('NOW')

np.datetime64('2025-07-09T15:39:58')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [59]:
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [64]:
a = np.ones((2,2))
b = np.ones((2,2))
np.add(a, b, out=b)
print(b)
np.divide(a, 2, out=a)
np.multiply(a, -1, out=a)
print(a)
np.multiply(a, b, out=a)
a

[[2. 2.]
 [2. 2.]]
[[-0.5 -0.5]
 [-0.5 -0.5]]


array([[-1., -1.],
       [-1., -1.]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [72]:
z = np.random.uniform(5, 10, 6)
print(z)
# 1 
print(np.floor(z))
# 2
print(z//1)
# 3
print(z - z%1)
# 4
print(np.trunc(z)) # it's not round off, it's just chop off the decimal

[5.78388695 9.81728714 6.44065915 9.28501745 5.14258939 6.07528522]
[5. 9. 6. 9. 5. 6.]
[5. 9. 6. 9. 5. 6.]
[5. 9. 6. 9. 5. 6.]
[5. 9. 6. 9. 5. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [75]:
z = np.tile(np.arange(0,5), (5,1))
z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [78]:
z = np.zeros((5,5))
print(z.shape)
z1 = np.arange(0,5)
print(z1.shape)
z += z1
z

(5, 5)
(5,)


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [85]:
def built_array(n):
    for i in range(10):
        yield i

gen = built_array(10)
for i in gen:
    print(i)

0
1
2
3
4
5
6
7
8
9


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [91]:
np.linspace(0, 1, num=11, endpoint=False)[1:]


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [97]:
z = np.random.choice(np.arange(10), 10)
z.sort()
z

array([0, 1, 1, 1, 2, 3, 5, 5, 5, 6])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
# uff

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [101]:
a = np.random.random(10)
b = np.random.random(10)
print(np.allclose(a,b))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [104]:
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [106]:
z = np.random.random(10)
print(z)
i = np.argmax(z)
print(i)
z[i]= 0
print(z)

[0.65279615 0.68834545 0.18034108 0.81045593 0.43284471 0.18735897
 0.37331904 0.56759546 0.29205681 0.01663453]
3
[0.65279615 0.68834545 0.18034108 0.         0.43284471 0.18735897
 0.37331904 0.56759546 0.29205681 0.01663453]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [107]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [125]:
a = np.random.choice(np.arange(1,10), (5,))
print(a)
b = np.random.choice(np.arange(1,10), (3,))
print(b)
c = 1 / np.subtract.outer(a, b)
print(c)

[1 3 5 5 3]
[4 2 1]
[[-0.33333333 -1.                 inf]
 [-1.          1.          0.5       ]
 [ 1.          0.33333333  0.25      ]
 [ 1.          0.33333333  0.25      ]
 [-1.          1.          0.5       ]]


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [126]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [129]:
int.max

AttributeError: type object 'int' has no attribute 'max'

#### 49. How to print all the values of an array? (★★☆)

In [132]:
# np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [138]:
z = np.random.randint(2, 10, 7)
print(z)
v = 5
i = np.argmin(z - v)
i

[9 5 9 2 9 9 7]


np.int64(3)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [6]:
Z = np.zeros(10, dtype=[ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z[0])
print(type(Z))
print(type(Z[0]))

(([0.0], [0.0]), ([0.0], [0.0], [0.0]))
<class 'numpy.ndarray'>
<class 'numpy.void'>


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [12]:
z = np.random.random((10,2)).astype(np.float32)
print(type(z[0][0]))
y = z.view(np.int32)
z = y
print(type(z[0][0]))


<class 'numpy.float32'>
<class 'numpy.int32'>


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [14]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [15]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [19]:
z = np.random.rand(4, 4)
z

array([[0.79833236, 0.30614735, 0.99300581, 0.50031668],
       [0.39287966, 0.36163762, 0.69318566, 0.6191567 ],
       [0.04334794, 0.08624978, 0.95566273, 0.82668008],
       [0.30235104, 0.93322259, 0.34900423, 0.71580738]])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [53]:
z = np.random.rand(2,4)
# z = z.view(np.float32)
z

array([[0.45922819, 0.02386269, 0.3526646 , 0.91053805],
       [0.51026929, 0.42638169, 0.25914446, 0.33098801]])

In [54]:
m = z.mean(axis=1)
m

array([0.43657338, 0.38169586])

In [56]:
for i in range(2):
    z[i] -= m[i]
z

array([[-0.41391857, -0.84928408, -0.52048216,  0.03739128],
       [-0.25312243, -0.33701004, -0.50424727, -0.43240371]])

In [58]:
z = z - z.mean(axis=1, keepdims=True)
z

array([[ 0.02265481, -0.41271069, -0.08390878,  0.47396466],
       [ 0.12857343,  0.04468583, -0.12255141, -0.05070785]])

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [64]:
z = np.random.randint(1, 10, (5,5))
print(z)
z.argmin()

[[2 4 7 5 3]
 [2 4 9 9 4]
 [6 5 9 2 2]
 [4 3 3 2 4]
 [1 4 5 5 8]]


np.int64(20)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [65]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [71]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)

[[63 45 61 46]
 [44 47 47 74]
 [73 59 71 60]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [73]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
print(Z0)
Z0[::nz+1] = Z
print(Z0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
a[[0,1]] = a[[1,0]]

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [1]:
import numpy as np

In [ ]:
z = np.random.randint(1,10, 20)
y = 

array([8, 4, 7, 2, 1, 8, 2, 3, 5, 1, 4, 5, 3, 1, 2, 1, 3, 1, 3, 9])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [5]:
Z = np.linspace(1,10,10)
R = np.array([Z[i:i+4] for i in range(len(Z) - 3)])
R

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  3.,  4.,  5.],
       [ 3.,  4.,  5.,  6.],
       [ 4.,  5.,  6.,  7.],
       [ 5.,  6.,  7.,  8.],
       [ 6.,  7.,  8.,  9.],
       [ 7.,  8.,  9., 10.]])

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
Z = np.ones((16,16))
k = 4

(4, 4)


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [7]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

571 ms ± 49.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
106 ms ± 327 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
96.2 ms ± 699 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)